# This workflow builds and uploads the pyMEAL package to PyPI using Twine
# Triggered manually via GitHub Actions UI

name: Build_PYMEAL_v7

on:
  workflow_dispatch:

jobs:
  python-build-n-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initialize Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install setuptools matplotlib pandas scipy numpy scikit-learn wheel 
          #pip install -r requirement.txt  # Ensure this file exists in your repo

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.ipynb_checkpoints
          # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.ipynb_checkpoints


      - name: Build source distribution
        run: python setup.py sdist

      - name: Build wheel distribution
        run: python setup.py bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          password: ${{ secrets.PYMEAL }}
          repository_url: https://upload.pypi.org/legacy/
